insert into application_user(version, id, username, hashed_password) values (1, 1,'Eula Lane', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 2,'Barry Rodriquez', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 3,'Eugenia Selvi', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 4,'Alejandro Miles', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 5,'Cora Tesi', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 6,'Marguerite Ishii', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 7,'Mildred Jacobs', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 8,'Gene Goodman', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 9,'Lettie Bennett', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 10,'Mabel Leach', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 11,'Jordan Miccinesi', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 12,'Marie Parkes', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 13,'Rose Gray', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 14,'Garrett Stokes', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 15,'Barbara Matthieu', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 16,'Jean Rhodes', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 17,'Jack Romoli', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 18,'Pearl Holden', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 19,'Belle Montero', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 20,'Olive Molina', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into application_user(version, id, username, hashed_password) values (1, 21,'lucky','$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')

insert into user_roles (user_id, roles) values ('1', 'USER')
insert into user_roles (user_id, roles) values ('2', 'USER')
insert into user_roles (user_id, roles) values ('3', 'USER')
insert into user_roles (user_id, roles) values ('4', 'USER')
insert into user_roles (user_id, roles) values ('5', 'USER')
insert into user_roles (user_id, roles) values ('6', 'USER')
insert into user_roles (user_id, roles) values ('7', 'USER')
insert into user_roles (user_id, roles) values ('8', 'USER')
insert into user_roles (user_id, roles) values ('9', 'USER')
insert into user_roles (user_id, roles) values ('10', 'USER')
insert into user_roles (user_id, roles) values ('11', 'USER')
insert into user_roles (user_id, roles) values ('12', 'USER')
insert into user_roles (user_id, roles) values ('13', 'USER')
insert into user_roles (user_id, roles) values ('14', 'USER')
insert into user_roles (user_id, roles) values ('15', 'USER')
insert into user_roles (user_id, roles) values ('16', 'USER')
insert into user_roles (user_id, roles) values ('17', 'USER')
insert into user_roles (user_id, roles) values ('18', 'USER')
insert into user_roles (user_id, roles) values ('19', 'USER')
insert into user_roles (user_id, roles) values ('20', 'USER')
insert into user_roles (user_id, roles) values ('21', 'USER')
